connectivity:
  spoke_networking:
    primary:
      virtual_network_name: "test-vnet-02"
      location: ${default_location}
      vnet_address_space: "10.0.0.0/16"
      rg_name: "test-rg-02"
      subnets:
        subnet1:
          name: "snet-test"
          address_prefix: "10.0.1.0/24"
          nsgs:
            name: "test-nsg"